### PR TITLE
Refactor Kubenetes dependencies into platform helper class

### PR DESCRIPTION
**Pull request by vaterlaus**
@stewartshea I did some testing/comparison against the results before the refactor and (after fixing some tricky bugs with the custom resource handling) they now give essentially the same results. The one difference is that the ordering of the groupings in the workspace file currently has dependencies on dict iteration order, which can change from run to run, so if you're just doing straight byte for byte file diffs of the old results vs the new one the workspace.yaml file will show up as different, but, at least from my semi-cursory eyeballing of it I think they have functionally the same contents.

I tried to build the docker image and test against that, but the build was stalling for me, seeming in the process of installing anthoscli. Does that ring any bells? I waited 20-30 min, but it seemed stuck in that place. Or does it just take a really long time to build now? So, anyway, I don't think any of my changes would affect how it behaves in the docker deployment model vs. my local development mode, but it's possible there's a regression there. Let me know if it's not working for you.

Again, since the changes in this PR are pretty pervasive, I'm assuming we're going to pound on it for a couple days to catch any possible regressions before we do the version bump.

Below are the more detailed comments from the commit:

- added new PlatformHandler class that's subclasses for different platforms to implement the platform-specific logic
- currently there's just the Kubernetes implementation but soon there will be other ones corresponding to new platforms that are indexable via CloudQuery
- added support for enum-based settings, specified by which enum class to use to represent the class, plus an optional constructor method to use to convert the value from the request data to the enum. As part of this I improved the error handling for the setting conversion code a bit to give better error messages if the user specifies an invalid value.
- switched the defaultLOD setting to be an enum setting backed by the LevelOfDetail class
- with this change users can now use the symbolic/string values for the level of detail settings instead of the previous not-super-user-friendly integer values (0="none",1="basic",2="detailed")
- the integer values are still supported, but deprecated
- got rid of the hclod enricher component, which previously just set up the level of detail values for the namespace resources. Now this is just done directly in the kubeapi indexer when it creates the resources (although I think probably the level of detail value shouldn't be stored in the resources and should just be handled directly in the gen rules code, but I'm leaving that change for later).
- cleaned up the way data is passed to match predicates to clean up some places that previously used global variables
- also implemented a generic visitor pattern for the match predicates to replace the previous hacky code that was used to collect all of the custom resource type references so that the indexer only need to handle custom resources that were referenced.
- this collector also collects the non-custom resource types that are accessed too, which will enable the indexers to be optimized a little more by only indexing the resource types that are accessed (although the kubeapi indexer isn't taking advantage of this yet).
- fixed a few more bugs that were fallout from the neo4j removal, e.g. some cases where it wasn't checking for a null resource type result from Registry.get_resource_type before trying to access the instances

### CODE REVIEW

**Comment by stewartshea** [comment]
I took a quick test on this but ran into errors. Need to spend more time testing to resolve them.

**Comment by stewartshea** [comment]
Error 500 from Workspace Builder service for command "run": 'Context' object has no attribute 'registry'

**Comment by stewartshea** [comment]
```
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '54139db2-901a-4c44-bfbb-2e90e0023e3a', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '3c78cabe-d2ec-4321-8c81-8716585af01f', 'X-Kubernetes-Pf-Prioritylevel-Uid': '92949591-29db-4806-b431-cb46f16c2b8d', 'Date': 'Tue, 28 Nov 2023 01:33:54 GMT', 'Content-Length': '393'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"prometheuses.monitoring.coreos.com is forbidden: User \"system:serviceaccount:viewer:runwhen-viewer\" cannot list resource \"prometheuses\" in API group \"monitoring.coreos.com\" in the namespace \"rwl-manifests\"","reason":"Forbidden","details":{"group":"monitoring.coreos.com","kind":"prometheuses"},"code":403}

, group=monitoring.coreos.com, kind=prometheuses
Finished Kubernetes indexing
  File "/workspace-builder/workspace_builder/views.py", line 102, in post
    run_components(context, components)

  File "/workspace-builder/component.py", line 347, in run_components
    component.run_func(context)

  File "/workspace-builder/enrichers/generation_rules.py", line 891, in enrich
    matches = generation_rule.match_predicate.matches(generation_rule_match_info)

  File "/workspace-builder/enrichers/match_predicate.py", line 79, in matches
    match = predicate.matches(match_info)

  File "/workspace-builder/enrichers/generation_rules.py", line 249, in matches
    return self.matches_resource(resource, context)

  File "/workspace-builder/enrichers/generation_rules.py", line 222, in matches_resource
    logger.debug(f"DEBUG: Match found for property {p} with name {name}")
```

**Comment by stewartshea** [comment]
Resolved the registry bug, but now I see a discrepancy  between the discovery from v0.3.14 (in the demo site) and this build
v0.3.14 Demo Site
```
1994 indexed commands across 1 cluster(s), 42 groups & 530 SLXs

Last generated at: 2023-11-28 00:20:46
For cluster(s): gke_runwhen-nonprod-sandbox_us-central1_sandbox-cluster-1-cluster
By: shea.stewart@runwhen.com
From: 3 community authors
```


Current Build
```
1508 indexed commands across 1 cluster(s), 40 groups & 423 SLXs

Last generated at: 2023-11-28 02:16:45
For cluster(s): gke_runwhen-nonprod-sandbox_us-central1_sandbox-cluster-1-cluster
By: shea.stewart@runwhen.com
From: 3 community authors
```

**Comment by stewartshea** [comment]
This might be a case where the demo site is deployed with some persistence, which due to some much needed clean up code, there is likely SLXs that are lingering. I diffed both SLX dirs and the demo site has multiple cert-manager and flux kustomize SLXs in the same namespace which should not be happening anymore. Reviewing further...

**Comment by stewartshea** [comment]
Interestingly a fresh install, the v0.3.14 site shows this (with an identical workspaceInfo.yaml)
```
1465 indexed commands across 1 cluster(s), 41 groups & 400 SLXs

Last generated at: 2023-11-28 03:09:41
For cluster(s): gke_runwhen-nonprod-sandbox_us-central1_sandbox-cluster-1-cluster
By: tester@my-company.com
From: 3 community authors
```

I'll continue analysis tomorrow

**Comment by stewartshea** [comment]
I have an example where a particular rule and the qualifiers appear to be treated differently between this build and v0.3.14. 

In this build, I see slx directories like this: 
```
drwxr-xr-x   2 999 root  58 Nov 28 11:22 vt-vl-grnwh-cert-health1
drwxr-xr-x   2 999 root  58 Nov 28 11:22 vt-vl-grnwh-cert-health2
drwxr-xr-x   2 999 root  58 Nov 28 11:22 vt-vl-grnwh-cert-health3
drwxr-xr-x   2 999 root  58 Nov 28 11:22 vt-vl-grnwh-cert-health4
drwxr-xr-x   2 999 root  58 Nov 28 11:22 vt-vl-grnwh-cert-health5
```
In v0.3.14 we only see a single instance: 
```
drwxr-xr-x   2 100998 sheastewart 4.0K Nov 28 06:16 vt-vl-grnwh-cert-health1

```
These are generated from the following genrule:
https://github.com/runwhen-contrib/rw-cli-codecollection/blob/main/codebundles/k8s-certmanager-healthcheck/.runwhen/generation-rules/k8s-certmanager-certificates-health.yaml

**Comment by stewartshea** [comment]
Comparing `vt-vl-grnwh-cert-health1` and `vt-vl-grnwh-cert-health2` (of which, there should only be one) - it looks like the they each have a unique fullSlxName annotation - so the qualifier somehow isn't being respected? 

## vt-vl-grnwh-cert-health1
### slx.yaml
```
apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: ws--vt-vl-grnwh-cert-health1
  labels:
    slx: ws--vt-vl-grnwh-cert-health1
    workspace: ws
  annotations:
    fullSlxName: vault-tls-vault-gke-runwhen-nonprod-sandbox-us-central1-sandbox-cluster-1-cluster-cert-health
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/cert-manager.svg
  alias: vault SSL Certificate Health
  asMeasuredBy: Certificates in an unready state
  configProvided:
  - name: OBJECT_NAME
    value: vault-tls
  owners:
  - tester@my-company.com
  statement: All certificates should be in a Ready state 99.5%. 
  additionalContext:  
    namespace: "vault"
    labelMap: "{'kustomize.toolkit.fluxcd.io/name': 'app-vault', 'kustomize.toolkit.fluxcd.io/namespace': 'flux-system'}"
    cluster: "gke_runwhen-nonprod-sandbox_us-central1_sandbox-cluster-1-cluster"
    context: "gke_runwhen-nonprod-sandbox_us-central1_sandbox-cluster-1-cluster
```


## vt-vl-grnwh-cert-health2
### slx.yaml
```
apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: ws--vt-vl-grnwh-cert-health2
  labels:
    slx: ws--vt-vl-grnwh-cert-health2
    workspace: ws
  annotations:
    fullSlxName: vault-tls-5fb4h-vault-gke-runwhen-nonprod-sandbox-us-central1-sandbox-cluster-1-cluster-cert-health
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/cert-manager.svg
  alias: vault SSL Certificate Health
  asMeasuredBy: Certificates in an unready state
  configProvided:
  - name: OBJECT_NAME
    value: vault-tls-5fb4h
  owners:
  - tester@my-company.com
  statement: All certificates should be in a Ready state 99.5%. 
  additionalContext:  
    namespace: "vault"
    labelMap: "{'kustomize.toolkit.fluxcd.io/name': 'app-vault', 'kustomize.toolkit.fluxcd.io/namespace': 'flux-system'}"
    cluster: "gke_runwhen-nonprod-sandbox_us-central1_sandbox-cluster-1-cluster"
    context: "gke_runwhen-nonprod-sandbox_us-central1_sandbox-cluster-1-cluster"
```

**Comment by stewartshea** [comment]
Interestingly, if I use the same example workspace of `vault`, I have two PVCs in there. The genrule here: https://github.com/runwhen-contrib/rw-cli-codecollection/blob/main/codebundles/k8s-pvc-healthcheck/.runwhen/generation-rules/k8s-pvc-healthcheck.yaml  uses the same type of qualifiers, and this build only produces a single a single SLX. So that would `imply` that the qualifier is working properly, at least in the case of the pvc genrule.

**Comment by stewartshea** [comment]
There is only 1 cert object in the vault namespace, and so the desire to generate multiple slxs doesn't make sense (even if `resource` was in the qualifier, which it isn't). I can confirm that the kubeconfig (the same used between this build and the tests with v0.3.14) can access the certificate object, and can list crds in the cluster. 
```
$ KUBECONFIG=/shared/kubeconfig kubectl get certificates.cert-manager.io -n vault          
NAME        READY   SECRET      AGE
vault-tls   True    vault-tls   236d
```

I've tried to make the cert generation rule look identical to the PVC example, and yet don't have a positive result. The only major difference that I can tell is that certificates.cert-manager.io are discovered through custom resources and persistentvolumeclaim is a core object (like a deployment or a statefulset)

**Comment by vaterlaus** [comment]
@stewartshea I pushed some tweaks to the fix for the dump_resources bug, mostly with removing some of the debug logging setup, which wasn't being used anymore, and even if it was, that's probably not the right place to put it.

I spent some time trying to reproduce the issues you were seeing with duplicate (?) SLXs showing up with the new stuff. For the 2 SLXs you commented on they had slightly different full SLX names with one of them having an extra "5fb4h" included in the name in the part that I think should be the namespace name based on the qualifiers but looks like that's maybe the name from the custom resource that was the matched resource. So possibly when the namespace qualifier is being used it's incorrectly using the name for the resource that was matched, not the name for that resource's part namespace. Is that what your diagnosis was too?

I tried to reproduce these problems with several of the kubeconfig I've gotten from you in the past, at least one of which I though was for the sandbox cluster, but none of them produced results like what you were posting, so I think I'm not indexing the same cluster that you're working with.

Also, after reading the whole thread I couldn't tell which of the issues you referred to earlier in the thread you still thought were real issues vs. possibly having something to do with your custom code collection not being applied correctly from the code collection configuration. Is that right? I'm sort of surprised that there would be an issue with that, though, because not that much changed in that part of the code, and what did change I would have thought would break everything if it was broken.

Anyway, let's talk about this some more when we talk after standup.

**Comment by stewartshea** [comment]
@vaterlaus Yeah, sorry, it was a bit of a journey through the thread. The fact that it wasn't reading from my custom codecollection really threw it off a bit. 

Based on your comment about bringing in the resource name into the namespace qualifier - I think this is exactly what is happening. The codebundle (in rw-cli-codecollection main) was looking for both certificates and certificaterequests, which makes sense as to why it created 5 resources (there was 1 certificate, and 4 certificaterequests), one of which has a name `vault-tls-5fb4h` - So I think this is the root of the issue. 

The other issue, as far as I can tell, is surprising in that it's somehow not overriding the codecollection from the workspaceInfo.yaml. I didn't see much in the way that the code was altered, but I could not seem to get this build to scan my fork instead of the default repo.

**Comment by vaterlaus** [comment]
@stewartshea With using the most recent sandbox kubeconfig you sent me I'm still not seeing the buggy behavior you observed with the qualified name seeming to incorrectly use the resource name instead of the namespace name. This was with the default and namespace LODs configured to only scan the "vault" namespace and the code collection config set to only enable the rw-cli code collection and only enable the "k8s-certmanager-healthcheck" code bundle, which I think is what you were doing too. So I'm still not sure what's going on there.

I did look again at what you were using for the code collection config to have your forked rw-cli-codecollection override the standard one and the syntax you're using isn't quite the way it's designed to be used. A few different things:

1) Probably for that use case the easiest thing to do would be to just explicitly specify the standard rw-public-codecollection as one entry and your forked rw-cli-codecollection as the second entry, and that's it. It won't implicitly include all of the code collections from the default/built-in list, so you don't need to try to do the negation of the standard rw-cli-codecollection to prevent it from being loaded.

2) If you specify a code collection entry with the special string value of "defaults", then that will include all of the entries from the default/built-in code collections. The use case for this is if you want to start with the built-in ones, but then just blacklist one or two of them. This is obviously not super applicable currently when there are only two built-in code collections but would be more useful in the future if/when we have more code collections that are built-in.

3) The syntax you are using with the ! intended to negate inclusion won't work for a couple of reason. First, the ! is only supported if you're using a simple string value for the code collection entry, not if you're using the format where it's a dict with labeled fields for everything. If you use the simple string format, then it uses the "main" branch and will include all of the code bundles. If you want to customize either of those things, then you need to use the dict/object format. So the config that would work that maps most directly from what you had would be something like:
```
codeCollections:
  - defaults
  - !https://github.com/runwhen-contrib/rw-cli-codecollection
  - repoURL: "https://github.com/stewartshea/rw-cli-codecollection.git"
    ref: debug-qualifiers
```
If you wanted to use the dict/object format to suppress something you can do that by including a label called "action" with a value of "exclude", but really in that case you're just suppressing the code collection by the repo URL, so using the string format with the leading ! will be the simplest way to do it.

But the simplest way to do it would be:
```
codeCollections:
  - https://github.com/runwhen-contrib/rw-public-codecollection
  - repoURL: "https://github.com/stewartshea/rw-cli-codecollection.git"
    ref: debug-qualifiers
```
Note that if you omit the "codeBundles" field then it includes all of the code bundles, so having the explicit single "*" pattern entry is unnecessary, since that's the default.

4) The thing that I still need to look into that I don't understand at this point is that the syntax you were using of putting the ! before the code bundle pattern seems like it should have had the effect of being a pattern that wouldn't match any code bundles, so it seems like it should have achieved the same result of essentially suppressing the entire code collection by suppressing the inclusion of any of its code bundles. But I sort of suspect that maybe something funky/buggy is going on with that since that wasn't something it was designed to support. So I'm sort of wondering if somehow you were still picking up the code bundles from the standard rw-cli repo, not your custom fork. And that maybe the standard repo is still using something like the resource name as the qualifier? Which could potentially lead to the some of the behavior you were seeing? Just sort of throwing out some possible diagnoses.

BTW, I also noticed in at least a few of the gen rule definitions (e.g. the one you linked to in one of the above comments)  that there was an unnecessary "and" match predicate wrapping the pattern predicate which is the one that's actually doing the work. The "and" and "or" predicate are only needed if you need to combine multiple pattern or exists predicates. I'm guessing maybe you kept that in during development when you were playing around with different forms of specifying the match predicates, but if we've settled on just the single pattern predicate it would be nice to go back and remove the "and" predicate, mostly just for increased readability of the gen rule.


I pushed a commit to fix the issues with cleaning up some Kubernetes-specific code in the map customization rules module that I missed the first time through. The changes included in this commit did touch on the code that handles the qualifier expansion to generate the full SLX name, so it's possible that there was a bug in the old code that was fixed when I cleaned up the stuff I missed before. Or it's certainly possible that the bug is still there :-) and I'm just not testing the with the exact same configuration that you are.

Anyway, if you have any cycles to test this some more, I'd be curious if you still see any of the problems if you use one of the code collection configs I suggested above. I'm going to spend a little time tomorrow trying to understand what was happening when you used the funky code bundle pattern with the !* pattern, because I'm curious how that could have caused the behavior you were seeing.

**Comment by stewartshea** [comment]
@vaterlaus I appreciate the clarity above on the codecollection configuration intentions and options. 

I can still consistently reproduce the issue with the current default codecollections. 
Given this `workspaceInfo.yaml`:
```
workspaceName: ws
# Tokens are generated from the RunWhen Platform UI if 
# planning on uploading workspace configuration
workspaceOwnerEmail: tester@my-company.com
defaultLocation: [placeholder]
defaultLOD: 0
namespaceLODs:
  kube-system: 0
  kube-public: 0
  kube-node-lease: 0
  vault: 2
custom:
  kubernetes_distribution: Kubernetes
  kubernetes_distribution_binary: kubectl
  
  # Possible values are gcp, aws
  cloud_provider: gcp
  
  # Possible values are gmp, promql
  prometheus_provider: gmp
  # If using GCP and wanting to use GCP integrations  
  gcp_project_id: runwhen-nonprod-sandbox 
  
  # Secret names are used when integrating the RunWhen Platform
  # with your enviornment. RunWhen has no access to this data, 
  # as the secret name and content comes from your own configuration. 
  kubeconfig_secret_name: kubeconfig
  gcp_ops_suite_sa: ops-suite-sa
```
and the kubeconfig I shared with you. 

From *this build*, I have these slxs: 
```
gitpod /workspace/local-test $ ls -lha shared/output/workspaces/ws/slxs/
total 4.0K
drwxr-xr-x 21 999 root 4.0K Nov 30 13:27 .
drwxr-xr-x  3 999 root   40 Nov 30 13:27 ..
drwxr-xr-x  2 999 root   74 Nov 30 13:27 vault-grnwhnnprsndbucntrl-ns-health
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vault-grnwhnnprsndbucntrl-sa-check
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vault-grnwhnnprsndbu-pvc-health
drwxr-xr-x  2 999 root   42 Nov 30 13:27 va-vl-grnwh-depl-health1
drwxr-xr-x  2 999 root   42 Nov 30 13:27 va-vl-grnwh-depl-health2
drwxr-xr-x  2 999 root   74 Nov 30 13:27 vi-vl-grnwh-htt-ok-tls-tst
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vi-vl-grnwh-ingress-health
drwxr-xr-x  2 999 root   58 Nov 30 13:27 vlt-grnwhnnprsndb-cert-health2
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vlt-grnwhnnprsndb-pod-resources
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vlt-vlt-grnwhnnpr-flux-helm1
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vlt-vlt-grnwhnnpr-flux-helm2
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vlt-vlt-grnwhnnpr-image-check
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vlt-vlt-grnwhnnpr-ss-health1
drwxr-xr-x  2 999 root   42 Nov 30 13:27 vlt-vlt-grnwhnnpr-ss-health2
drwxr-xr-x  2 999 root   58 Nov 30 13:27 vt-vl-grnwh-cert-health1
drwxr-xr-x  2 999 root   58 Nov 30 13:27 vt-vl-grnwh-cert-health2
drwxr-xr-x  2 999 root   58 Nov 30 13:27 vt-vl-grnwh-cert-health3
drwxr-xr-x  2 999 root   58 Nov 30 13:27 vt-vl-grnwh-cert-health4
drwxr-xr-x  2 999 root   58 Nov 30 13:27 vt-vl-grnwh-cert-health5
```

From v0.3.14, same workspaceInfo.yaml and same kubeconfig, I have these slxs
```
 sheastewart@sheacer  ~/runwhen-local  ls -lha shared/output/workspaces/t-sandbox/slxs 
total 84K
drwxr-xr-x 21 100998 sheastewart 4.0K Nov 30 08:27 .
drwxr-xr-x  3 100998 sheastewart 4.0K Nov 30 08:27 ..
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 grnsucsc1c-cpu
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 grnsucsc1c-disk
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 grnsucsc1c-mem
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vault-grnwhnnprsndbucntrl-ns-health
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vault-grnwhnnprsndbucntrl-sa-check
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vault-grnwhnnprsndbu-pvc-health
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 va-vl-grnwh-depl-health1
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 va-vl-grnwh-depl-health2
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vi-vl-grnwh-htt-ok-tls-tst
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vi-vl-grnwh-ingress-health
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vi-vlt-grnwhnnpr-ngx-ing-gmp
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vlt-grnwhnnprsndb-cert-health2
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vlt-grnwhnnprsndb-pod-resources
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vlt-vlt-grnwhnnpr-flux-helm1
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vlt-vlt-grnwhnnpr-flux-helm2
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vlt-vlt-grnwhnnpr-image-check
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vlt-vlt-grnwhnnpr-ss-health1
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vlt-vlt-grnwhnnpr-ss-health2
drwxr-xr-x  2 100998 sheastewart 4.0K Nov 30 08:27 vt-vl-grnwh-cert-health1

```

Focusing on `vt-vl-grnwh-cert` we can see that this build is still creating 5 distinct SLX objects, when only 1 is expected based on the qualifiers. This current validation requires no tweaking to codebundles as we can see the discrepancy  between **v0.3.14** and **this build**. In some way, my feeling is that the issue might lie somewhere in how the custom resource is handled and applied to the qualifiers- as this issue doesn't seem to come up with something like the PVC objects (in which a namespace has many, but this build only produces the desired single SLX).

**Comment by stewartshea** [comment]
@vaterlaus 

So, when I *only* have this custom codecollection configured, I am getting the result I expect and the custom codecollection appears to be used properly: 
```
codeCollections:
  - repoURL: "https://github.com/stewartshea/rw-cli-codecollection.git"
    ref: debug-qualifiers
```

This led me to find a conflicting genrule in https://github.dev/runwhen-contrib/rw-public-codecollection. And it now all makes sense..... apologies for the journey we've been on. 

This leads me to believe we need some way of indicating/attaching the genrule source data into the object when we create it. Since the genrule lives with the codecollection, this is likely necessary as people start to use even more than 2 codecollections.

**Comment by vaterlaus** [comment]
@stewartshea I pushed a commit that includes info about the source gen rule as annotations in the slx/sli/runbook files. It's somewhat redundant to include the repo URL and ref values there, since there typically specified elsewhere in the spec, but I think it will be convenient to have them there as explicit annotations to help when tracking down gen rule issues.

The issue you were hitting with the parsing of the code collection data when using the ! to negate the inclusion of a code collection is a problem with the yaml parsing of the leading ! char, which it doesn't like for some reason I'm not sure of. Anyway, the fix is to just put quotes around the string to make it happy.

**Comment by stewartshea** [comment]
Codebundles that didn't match/produce results in this build: 
- https://github.com/runwhen-contrib/rw-public-codecollection/blob/main/codebundles/gcp-opssuite-promql/.runwhen/generation-rules/nginx-ingress-http-errors-gcp-promql.yaml
- https://github.com/runwhen-contrib/rw-public-codecollection/blob/main/codebundles/kong-ingress-health-gcp-promql/.runwhen/generation-rules/kong-ingress-health-gcp-promql.yaml
- https://github.com/runwhen-contrib/rw-public-codecollection/blob/main/codebundles/gcp-opssuite-promql/.runwhen/generation-rules/flux-reconciler-gcp-promql.yaml
- https://github.com/runwhen-contrib/rw-public-codecollection/blob/main/codebundles/gcp-opssuite-promql/.runwhen/generation-rules/gke-cluster-health-generation-rule.yaml

@vaterlaus all of the above genrules rely on a specific `and` predicate match that includes: 
```
            - resourceType: variables
              type: pattern
              pattern: "gcp"
              properties: [custom/cloud_provider]
              mode: substring
```

This seems to be common across those rules. Do you have think that this particular match configuration is getting skipped/not matched in this build?

**Comment by vaterlaus** [comment]
@stewartshea I think my most recent commit should fix the issue you were seeing with the discrepancy with a few of the gen rules. This turned out to be a regression in the evaluation of the custom variable match predicates. I reworked the way all of that worked, because the old code was really hacked up (you can read the commit message for more details). Let me know if the output still doesn't match up what you see with the previous version.

One outcome of that reworking, though, was that I realized we don't have a great backward compatibility approach currently. In particular, now that the gen rules are in the code collections and decoupled from the workspace builder code, we don't have a good way of adding new generation rule features in the workspace builder code and adopting them in the gen rule definitions in the code bundles without breaking users who are using older versions of the workspace builder.

I can think of a number of different things we could do to handle this, but I don't think we need to go too overboard on it. I think probably just having some sort of versioning scheme, so we can detect if a gen rule is using newer features than the workspace builder that is interpreting them and just ignoring those gen rules (and probably emitting a warning message that some gen rules were skipped and that the user should upgrade to a newer version). Or something like that...

**Comment by stewartshea** [comment]
Thanks for the fix and your notes around versioning of the gen rule, let's add that to the issue backlog. 

I tested this latest version against 0.3.14 with identical results, thanks!!

**Review by stewartshea — APPROVED** [review]

**Pull request merged**
